// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREDC8-xaA4StvJBuMrpJvkHK1ua9kN5U',
    appId: '1:81953872588:android:3ab48f1f46e23d5fa18069',
    messagingSenderId: '81953872588',
    projectId: 'logs-laggedskapari',
    storageBucket: 'logs-laggedskapari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9qsyZY7P2xXPmiecw3n4taVN8D27yeI',
    appId: '1:81953872588:ios:5787942aa6876079a18069',
    messagingSenderId: '81953872588',
    projectId: 'logs-laggedskapari',
    storageBucket: 'logs-laggedskapari.appspot.com',
    iosBundleId: 'com.example.logs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9qsyZY7P2xXPmiecw3n4taVN8D27yeI',
    appId: '1:81953872588:ios:b1818beb8a8c747ea18069',
    messagingSenderId: '81953872588',
    projectId: 'logs-laggedskapari',
    storageBucket: 'logs-laggedskapari.appspot.com',
    iosBundleId: 'com.example.logs.RunnerTests',
  );
}
