// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkdtaTXqz7QZn8pbGBha6_vnDnuvnE18',
    appId: '1:526998331555:web:357a0d4c3067df048fdf16',
    messagingSenderId: '526998331555',
    projectId: 'cross-laggedskapari',
    authDomain: 'cross-laggedskapari.firebaseapp.com',
    storageBucket: 'cross-laggedskapari.appspot.com',
    measurementId: 'G-VFZYNY1Y4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9irS0FE29KHMd1uSMlX8girMcj4uAcs',
    appId: '1:526998331555:android:7d446b8c0f2d06c78fdf16',
    messagingSenderId: '526998331555',
    projectId: 'cross-laggedskapari',
    storageBucket: 'cross-laggedskapari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMqCinERA2AoRHwW21JOj6Zyetst2RZxs',
    appId: '1:526998331555:ios:59c61acf12e4354a8fdf16',
    messagingSenderId: '526998331555',
    projectId: 'cross-laggedskapari',
    storageBucket: 'cross-laggedskapari.appspot.com',
    iosBundleId: 'com.example.crossFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMqCinERA2AoRHwW21JOj6Zyetst2RZxs',
    appId: '1:526998331555:ios:7bbffc4f5be5199f8fdf16',
    messagingSenderId: '526998331555',
    projectId: 'cross-laggedskapari',
    storageBucket: 'cross-laggedskapari.appspot.com',
    iosBundleId: 'com.example.crossFlutter.RunnerTests',
  );
}
